language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t skullcutter02/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skullcutter02/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-test"
  env: "Dockerreacttest-env"
  bucket_name: "elasticbeanstalk-us-east-2-740995310974"
  bucket_path: "docker-react-test"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

